### ISSUE TITLE
Requirements.txt is not complete

### ISSUE THREAD

**Issue by Mosc5** [rl-institut/simbev#1]

**Comment by nesnoj** [comment]
@Mosc5 you added specific package versions in your initial reqs file:
```
pandas~=1.1.3
numpy~=1.19.2
setuptools~=52.0.0
```
As I merged the refactoring stuff from master into dev, I decided to use those of @stefansc1 for now.
But in general it is a good idea to have at least lower and upper bounds to make sure the tool won't break due to API changes of future versions. We should get back to this again later!
